version: '3'

services:
  producthunt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producthunt
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    
